# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e67f35cbaf3d5c57c570d1fb1b938c7587f5563d9e8fadb5f89f106baa9b58e8f7adad86b499dba1949285d66a954941f4bd4afd140743e57db5ddd465d3ffab

test:
  secret_key_base: c94b9df9a0339c5b5b60f9968cbe73f5c64a259e51cf3cb33c2ae13de1b6ec900f315153322d90b95935e51422ef43e626f1d40590e0523011ac9fce953bc455

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
